### ISSUE TITLE
I got access to your GMAIL.

### ISSUE THREAD

**Issue by saraiva1989** [dotronghieu/CapstoneProject#1]
@dotronghieu @nguyenchien789 
Hi, my name is Daniel and I'm a developer in Brazil.
I got access to your GMAIL.

I work looking for vulnerability on people's websites and helping to solve for free.

        public struct Roles
        {
            public const int ROLE_ADMIN_ID = 1;
            public const int ROLE_USER_ID = 2;
            public const string ROLE_ADMIN = "Admin";
            public const string ROLE_USER = "User";
            public const string IMAGO_EMAIL = "imagoworkplace@gmail.com";
            public const string IMAGO_EMAIL_PASSWORD = "sa@123456";
        }

But if you can help with any amount I would be very happy and grateful.

Follow my paypal account details

https://www.paypal.com/donate?hosted_button_id=EN9JK4LL787AA

If you can't make the donation, help a person with a hug :-)

**Comment by dotronghieu** [comment]
O my god, how can you get that....I am working on a project for 4th college
year so I have to send email for confirmation gmail account.

Vào CN, 31 thg 1, 2021 lúc 22:48 Daniel Saraiva <notifications@github.com>
đã viết:

**Comment by saraiva1989** [comment]
@dotronghieu 

Come on, do you want to keep this repository public?

If so, you will have to:
1 - Download the code to your local machine
2 - Delete the github repository
3 - Create a new repository
4 - upload your code, but not putting SMTP information in the public repository. You upload the right connection data to your server but on github it leaves without.

you can also put two-step validation in your email, so I wouldn't have full access.

Now if you don't want to leave the repository public, just set it to private so that no one will see the SMTP connection in your code.


In short, the mistake you made was putting the SMTP connection data in your code and uploading it to github. So anyone who sees your repository can read your code

**Comment by dotronghieu** [comment]
Awesome, thanks you very much

Vào CN, 31 thg 1, 2021 lúc 23:29 Daniel Saraiva <notifications@github.com>
đã viết:
